### ISSUE TITLE
Pessimist and Optimist must be switched

### ISSUE THREAD

**Issue by viniciusoyama** [pippinbarr/SNAKISMS#1]
Hi! Congratz for the game. It's very fun.

IMO the "optimism" version and de "pessimism" version are inverted. 

In the current pessimism version the snake keeps moving even if there is no way to eat the apple. I think that it's being pretty optimistic, no?

The same idea applies to the optimism version: when the snake keeps moving in a area full of apples and never grows, it is enjoying its big luck. To be pessimistic it should do not eat the apple (because it thinks that the apple doesn't exists) and grows anyways..

What do you think? 

:)

**Comment by pippinbarr** [comment]
Hah! I love that you opened this as an official issue with the game. I think the reinterpretation is pretty interesting actually, and I'm a big fan of the fact that game *can* be reinterpreted at all.

Heh. I think I'll stick with the way it is, but if you want to clone and "fix" it you are most welcome :)
